### ISSUE TITLE
TableCell errors are clogging the console

### ISSUE THREAD

**Issue by erasta** [argosp/trialdash#101]
I'm getting a lot of css-like classes errors on the map, and it's clogging the console.
Can you handle them please?

example:   
index.js:1437 Material-UI: the key `tableBodyRow` provided to the classes prop is not implemented in ForwardRef(TableCell).
You can only override one of the following: root,head,body,footer,sizeSmall,paddingCheckbox,paddingNone,alignLeft,alignCenter,alignRight,alignJustify,stickyHeader.

**Comment by YehuditGrinwald** [comment]
@erasta Please provide when/where do you get these errors

**Comment by erasta** [comment]
> @erasta Please provide when/where do you get these errors

happens only when i run it locally, and on every page, for instance:
http://localhost:3000/experiments/5dc17752abba6cf7e4b698cd/trial-sets/4d6e0c4c-8f2c-4b23-867e-2be7c483ddcd/trials
![image](https://user-images.githubusercontent.com/7118772/96421293-46f92d80-11ff-11eb-90ce-d5da210673e1.png)

loads of errors like this:
![image](https://user-images.githubusercontent.com/7118772/96421354-59736700-11ff-11eb-8d75-3c14334fd1bc.png)

**Comment by YehuditGrinwald** [comment]
Check:
- Missing props in material ui components.
 - or material ui version
