### ISSUE TITLE
add clone devices button on trial edit mode

### ISSUE THREAD

**Issue by YehuditGrinwald** [argosp/trialdash#105]
![image](https://user-images.githubusercontent.com/24703036/95857955-06179980-0d65-11eb-980d-277413511091.png)
onClick button display menu of experiment and option to choose between design/ deploy.

**Comment by YehuditGrinwald** [comment]
@yehudarav 
The task is to clone **devices** from **trial**.
Clone devices from trials of current trial set? or all trials?

The flow should be like:

- [ ] Choose trial to clone from.

- [ ] Choose trial status to clone from design / deploy.

- [ ] Save btn onclick will copy the devices from the trial to the selected trial.

**Comment by yehudarav** [comment]
For now only the trials of the current trialset

**Comment by yehudarav** [comment]
The flow should be 

choose the trial and then click on design or deploy. after the selection the devices will be copied. 
The devices should be copied to the current state of the trial.

**Comment by YehuditGrinwald** [comment]
@yehudarav done.
