### ISSUE TITLE
Saving images from ExperimentForm maps

### ISSUE THREAD

**Issue by erasta** [argosp/trialdash#112]
currently images are saved as imageUrl for each row a json.
On the server that json needs to be transformed:
1. JSON.parse the `maps` string
2. for each row get the `imageUrl` field, and check if that is an image url or a server file url
3. save the image of that imageUrl to an image file on the server, as jpg or png file, to some folder.
4. change the `imageUrl` field to a url of the file saved.
5. JSON.stringify back into the `maps`

also:
6. check that there are no files on that server folder that doesn't have an `imageUrl` item on **any** `experiment`.
otherwise the server filesystem will be bloated.

**Comment by YehuditGrinwald** [comment]
1. `onSubmitExperiment` function -delete tmp images that uploaded and not saved in row.
3. `generateFileName` function - create new random file name. (at uploadFile function in graph)
