### ISSUE TITLE
Experiment data to DevicePlanner

### ISSUE THREAD

**Issue by erasta** [argosp/trialdash#114]
`DevicePlanner` needs the `ExperimentForm.maps` field.
To get that, the experiment data object needs to be given to `DevicePlanner`

**Comment by YehuditGrinwald** [comment]
done.
get the data by `experimentDataMaps` property

**Comment by erasta** [comment]
can't read experiments on production, please fix.

**Comment by YehuditGrinwald** [comment]
fixed.
