### ISSUE TITLE
Update master branch

### ISSUE THREAD

**Issue by kaplanlior** [argosp/trialdash#120]
I'd like to replace master branch with master-eran branch, as this new branch uses the correct email address for Eran.
Code/commit wise - it's the same.

As this change would require to rebase the feature branches, I want to coordinate the timing of the replacement.
@erasta @YehuditGrinwald 

(any new commits to master would be taken as well before switching branches).

**Comment by erasta** [comment]
Is there no way to do this by multiple commit amend on the current master branch?

**Comment by kaplanlior** [comment]
No, we can't

**Comment by kaplanlior** [comment]
Branches switched. Old master branch kept as master-backup (just in case).

Just "git pull -r" on your existing master branch to align it with the change
