### ISSUE TITLE
Display all devices of current trial in device planner view

### ISSUE THREAD

**Issue by YehuditGrinwald** [argosp/trialdash#129]
Currently not all devices are displaying. (attach screenshot)   
@erasta Please note - display the `entities`/ `deployedEntities` according to the `trial.status ` 
![devicesArgos](https://user-images.githubusercontent.com/24703036/102095300-0ba86300-3e2c-11eb-9785-4b0e134bd2a9.png)

**Comment by erasta** [comment]
Changed device planner to use the right entities according to the trial status (deployed/design as on the parent component TrialDevices).
This is however not showing more devices, just changing their locations.

**Comment by erasta** [comment]
now query returns devices from all trials, locations are only from the current trial.
