### ISSUE TITLE
deviceMutation function

### ISSUE THREAD

**Issue by erasta** [argosp/trialdash#13]
In DevicePlanner/utils there is deviceQuery()
Please create a similar function that changes the data on a device.
The changes can be addition, change or removal of fields.
Please also supply an example how to use that function.

**Comment by erasta** [comment]
Found deviceMutation but didn't quite understand how to use it.
Prepared a placeholder to call it with the changed devices, instead of the console.log:
https://github.com/argosp/trialdash/blob/1df6aff0badd9492606139d5328d1fc2745577dc/src/components/DevicePlanner/index.jsx#L60

**Comment by rivkatzur** [comment]
@erasta 

An example how to use deviceMutation
https://github.com/argosp/trialdash/blob/1df6aff0badd9492606139d5328d1fc2745577dc/src/components/DeviceContext/DeviceForm/index.jsx#L90
