### ISSUE TITLE
Experiments with images should have a map placement as well

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#130]
In the leaflet, the experiments that have images should allow placement on a map as well. 
That is, the menu on the side of the leaflet should have:

* map 
* Image 1 name
* Image 2 name 
* ... 

When placing the device, the name of the figure (or OSMmap) should be saved in the location name.

**Comment by erasta** [comment]
not sure i understood, can you explain? @yehudarav

**Comment by yehudarav** [comment]
When I add pictures with out embedding I don't get the option to save devices to the map. 

See for example Experiment NTA/Release Tests 

![Screenshot from 2021-02-23 13-45-37](https://user-images.githubusercontent.com/50652905/108839239-7bca2680-75dd-11eb-93ce-497bbb28e98a.png)

**Comment by erasta** [comment]
done
