### ISSUE TITLE
Crash when adding new trials/edting devices. 

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#132]
The web crashes (empty screen) when trying to add trials/experiments.

**Comment by YehuditGrinwald** [comment]
typeError: Cannot read property 'val' of undefined

**Comment by YehuditGrinwald** [comment]
![image](https://user-images.githubusercontent.com/24703036/108352632-ccadd980-71ef-11eb-8747-31878859f950.png)
Check error when devices list is empty.
