### ISSUE TITLE
Update the logic of entering coordinates for non-embedded pictures

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#134]
The workflow for non-embedded pictures should be: 

1. Set 'Drag on Image' to false. 
2. Select the location of the point with the known coordinates.  
3. Set the Lat/Lon to be the coordinates of the point that was selected. 

However, when Lat/Lon are set (for example to 0,0) the entire picture changes, rather then just set the coordinates. 

For example: 

Step 1. 
![Screenshot from 2021-02-17 16-47-40](https://user-images.githubusercontent.com/50652905/108220899-e4c62000-713f-11eb-97ce-dcf66eee489a.png)

Step 2. 
![Screenshot from 2021-02-17 16-47-07](https://user-images.githubusercontent.com/50652905/108220911-e7c11080-713f-11eb-82fe-d101908e24f0.png)

Step 3. 
![Screenshot from 2021-02-17 16-33-51](https://user-images.githubusercontent.com/50652905/108220913-e859a700-713f-11eb-9d49-c9cf7d71f1e6.png)

**Comment by erasta** [comment]
this should be ok now
@yehudarav
