### ISSUE TITLE
Save the location of the map in the device placement

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#136]
In the current implementation the coordinates of the images are placed in the coordinates of the map. 
Since the image coordinates are usually around 0,0 the map will be centered around the Africa. 
Then when the image is switched back to the map it is centered around the wrong location. 

The solution is to save the  location of the map and switch to its coordinates. 
Also, to center around the image

**Comment by yehudarav** [comment]
It should also focus on the image. 
Currently, I sometimes see the edge of the image when I try to save devices to it. 

See the NTA/Release tests.

**Comment by erasta** [comment]
Moving to the correct image bounds according to layer.
But still not remembering.
Currently always returning to Tel-aviv when going to OSMMap
