### ISSUE TITLE
Image control points flip

### ISSUE THREAD

**Issue by erasta** [argosp/trialdash#137]
When moving the lower right point to above the upper left point, the later moves its position.
The new position Y is equal to height-Y.
This happens because the diagonal is now flipped.
To keep the point position the image should be flipped as well,
If that is not reasonable, we need to find a better solution.
example:
![image](https://user-images.githubusercontent.com/7118772/108704227-63daa000-7514-11eb-93ae-542a7fed9ee9.png)
![image](https://user-images.githubusercontent.com/7118772/108704252-6ccb7180-7514-11eb-981e-9bc1979857a3.png)

**Comment by yehudarav** [comment]
I really don't understand why. 

All we want is to say that at point (x1,y1) the coordinate is (A,B)  and in point (x2,y2) the coordinate is (C,D). 

Why do we need to flip anything?

**Comment by erasta** [comment]
i think this is better now, please check 
@yehudarav
