### ISSUE TITLE
Refresh needed after setting devices

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#138]
Just switching to the table mode and back does not display the new devices. 

However, after refreshing the right devices are displayed. 

Similarly, when pressing the save button at the bottom of that page it does not save but just returns to the trial editing. 
I think we can remove the save button from there. 

![Screenshot from 2021-02-23 13-45-37](https://user-images.githubusercontent.com/50652905/108840190-a7014580-75de-11eb-8742-b27f7b05b518.png)

**Comment by yehudarav** [comment]
I think we can remove the entire footer. Is it necessary for something there?

**Comment by rivkatzur** [comment]
@yehudarav 

delete - delete the trial
cancel - return to trials list without saving, in the map the points saved already

So I remove the entire footer from the map page
