### ISSUE TITLE
Devices seems unassigned when changing image 

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#143]
When devices are assigned to a certain device we get the assign icon on their right. However, when changing the image to another location, they seem unassigned. 

Solution: maybe change the color of the assigned icon to show that the devices are assigned in another map?

**Comment by erasta** [comment]
on this layer, icon is green
on another layer, icon is grey
also, there is a tooltip
![image](https://user-images.githubusercontent.com/7118772/109970733-145b5780-7cfe-11eb-9dc7-14de4fc1b26c.png)
