### ISSUE TITLE
Add coordinate pointer to the non-embedded images

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#144]
When assigning devices to images, show some the coordinate (grid? tooltip? both?). 

if we choose grid, then it should be optional to define its spacing. (I think that it should be equidistant).

**Comment by erasta** [comment]
if you click one of the black points it shows you their location.
or do you want to other indication?
what would feel most natural to you? @yehudarav 
![image](https://user-images.githubusercontent.com/7118772/109947461-013a8e80-7ce2-11eb-88ea-06390e14e12e.png)
