### ISSUE TITLE
graphQL returns deleted experiments

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#145]
Using the graphQL 
        {
            experiments{
                id
                name
                description
                status
            }
        }

returns 65 projects, while only 6 projects are shown in the GUI

**Comment by yehudarav** [comment]
The returned experiments are not related to the ones in the GUI. 
The description and ect are different.

**Comment by rivkatzur** [comment]
In react we use this query:

{
  experimentsWithData {
    id
    name
    description
    begin
    end
    location
    numberOfTrials
    key
    state
    status
    project {
      id
      name
      description
    }
    maps {
      imageUrl
      imageName
      lower
      upper
      left
      right
      width
      height
      embedded
    }
  }
}

**Comment by yehudarav** [comment]
But it seems that you should get the same results, but with more data. 

When you run my query do you get all the deleted and not updated experiments as well?

**Comment by yehudarav** [comment]
ok I see the problem, I used experiments and not experimentsWithData.
