### ISSUE TITLE
Device placements lines at wrong position

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#147]
When setting up devices in a poly, the lines of the poly (and the label of the distance) 
is not coordinates with the positions that the user selects. 

Note the difference between the black circles (user selection) and the location of the lines (blue lines). 
The placement of the devices is ok (according to the black points 

![Screenshot from 2021-03-24 15-21-49](https://user-images.githubusercontent.com/50652905/112317778-0f624600-8cb5-11eb-8ab7-80f9624c35bf.png)

**Comment by erasta** [comment]
fixed https://github.com/argosp/trialdash/commit/39f63954811a4ded686ebde34ab7847cf496ea12

**Comment by erasta** [comment]
now it should be ok https://github.com/argosp/trialdash/commit/201ebe059ba8aa5ec9184e5b76385e0bb6b0fcb7
