### ISSUE TITLE
Opening device tables crashes

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#154]
The site crashes when trying to display the devices table

![Screenshot from 2021-04-07 16-44-26](https://user-images.githubusercontent.com/50652905/113876863-d18b1480-97c0-11eb-9357-695020093dc0.png)

**Comment by rivkatzur** [comment]
@yehudarav 
I can't reproduce  
I need more info

**Comment by yehudarav** [comment]
1. Goto to the NTA experiment
2. Open the only trial there (release001).
3. Open the placingnon map.
4. Goto the table and try to open thenkaijo or ndir tab

**Comment by rivkatzur** [comment]
@yehudarav   
This happens because the device that was associated with the trail was deleted
 
When deleting a device, should we delete all his entities in Trails?

**Comment by yehudarav** [comment]
I think so. Yes
