### ISSUE TITLE
Adding grid on the map placement

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#155]
Add a folding menu on the left side, that would allow to display grid (a true false) and determine its spacing (a single number). 
Maybe we will change the entire left menu to folding menu with the headings: 

[Device placement] 
The current menu
[Grid] 
Setting of grid.

**Comment by erasta** [comment]
On the device editor of non-embedded images
Show an optional grid
The grid is centered at (0, 0)
allow setting the scale of the grid
Default grid square is 1 meter.

**Comment by erasta** [comment]
works well on images with low actual length (10 meters).
In the meantime i put the controls on the left panel, that can move to a custom control later.
On images with bigger actual length, like in NTA, leaflet uses meters as lat/long and the lines curve.
![image](https://user-images.githubusercontent.com/7118772/115955028-e4118780-a4fc-11eb-8b34-e71381bc34ef.png)
![image](https://user-images.githubusercontent.com/7118772/115955101-54200d80-a4fd-11eb-95b2-bb70584eb608.png)

**Comment by erasta** [comment]
looks fine to me.
you can close this issue, unless you want me to put some numbers on it ;-)
