### ISSUE TITLE
Problems with setting the dimension  of images

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#156]
The mechanism for setting the dimension doesn't work well. Setting the image coordinates distorts the image and the control points move. Also, it provides too much freedom for the user. 

I suggest to have a 3-point system as a right-angle  triangle. 
The corner of the right angle will be the (0,0). Then the right and top points could be used to determine the position on the map 
and the number on the left menu could be used to determine the distance.

**Comment by erasta** [comment]
not sure i understood, can you draw a diagram or call me to explain? thanks
@yehudarav

**Comment by erasta** [comment]
The problem is that when you change the number it immediately changes the view.
Therefore "10." changes to "10".
Solution: I will give a small timeout, like 500ms between edit and changing the view.

**Comment by erasta** [comment]
We talked and decided that on non-embedded images there will be a different mechanism:
- Anchor point, as a default on 0,0 and on the center of the image
- You can edit the pixel (x, y) and the meter (x, y) of the anchor by dragging and by setting the numbers on the text field
- Two more points, one horizontal and one vertical of the anchor.
- Each point you can drag along its axis.
- Each point you can edit its distance in pixels or in meters.

**Comment by erasta** [comment]
refactoring https://github.com/argosp/trialdash/commit/18ba04d9cb20c9d6ce10e79266f25359e7779e10 before splitting embedded and standalone ui.

**Comment by erasta** [comment]
fixed as requested
