### ISSUE TITLE
The distance in the image placing is only integer

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#157]
Please allow fraction as a distance when setting the dimensions of an image.

**Comment by erasta** [comment]
Looks like you can have fractional numbers on all fields.
Or did i not recreate the problem correctly?
@yehudarav 
![image](https://user-images.githubusercontent.com/7118772/115198525-d0c87b80-a0fa-11eb-99b9-28e7925a2da3.png)

**Comment by erasta** [comment]
The problem is that when you change the number it immediately changes the view.
Therefore "10." changes to "10".
Solution:
I will give a small timeout, like 500ms between edit and changing the view.

**Comment by erasta** [comment]
done https://github.com/argosp/trialdash/commit/a7ef2b724c2a4f3bf261d8ceac98a3413c02d51f

**Comment by yehudarav** [comment]
great.
