### ISSUE TITLE
Small notes in determining the image dimensions size

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#161]
Hi, 

Some small notes:

- [x] 1. The text boxes with 'meters' (Horizontal meters) overlaps with the numbers. Needs a bit more spacing. 
- [x] 2. The User should determine the horizontal and vertical **distance**, and therefore it should be only positive. So it doesn't matter if the point is to the left or right, the vertial/horizontal distance must be 0. 
- [x] 3. The default coordinates of the anchor shold be (0,0).

**Comment by erasta** [comment]
Regarding 2nd point: 
Currently i gave the option to put the point to the right or left of the anchor, when left, this should use negative distance.
But i can fix so it will use the positive distance.

Didn't understand what you meant with 0.
@yehudarav

**Comment by erasta** [comment]
![image](https://user-images.githubusercontent.com/7118772/115766154-4b6df100-a3b0-11eb-8460-988773f35852.png)

**Comment by yehudarav** [comment]
See the NTA experiment, the concourse image. 

I still have the following problems: 
- [ ]  1. The anchor does not start at 0,0
- [ ]  2. Setting (0,0) for the anchor does not work
- [ ]  3. Setting the vertical meters, changes the anchor and does not (it seems to work for the horizontal).

**Comment by erasta** [comment]
> * [x]   1. The anchor does not start at 0,0
> * [x]   2. Setting (0,0) for the anchor does not work
> * [x]   3. Setting the vertical meters, changes the anchor and does not (it seems to work for the horizontal).

Couldn't reproduce any of those problems, i think it is already fixed.

**Comment by erasta** [comment]
everything should be ok now, i checked but please recheck that also. @yehudarav
