### ISSUE TITLE
Editing images crushes site

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#168]
Edit the image in the setup of the experiment  (just clicking the pencil icon) crushes the site.

**Comment by rivkatzur** [comment]
@yehudarav 
Can't reproduce
I need more details

**Comment by yehudarav** [comment]
1. Edit an experiment (any experiment will do, but lets choose NTA) 
2. Press on edit picture. 
3. Site crushes. (whether a new or old image). 

![Screenshot from 2021-05-10 11-09-00](https://user-images.githubusercontent.com/50652905/117626881-423a9d80-b180-11eb-89fd-1c9ef155a567.png)

**Comment by rivkatzur** [comment]
![Screenshot from 2021-05-10 13-30-07](https://user-images.githubusercontent.com/6241247/117645980-e843d300-b193-11eb-
8d6f-e9ed5f3bcab9.png)
![Screenshot from 2021-05-10 13-31-50](https://user-images.githubusercontent.com/6241247/117646132-19bc9e80-b194-11eb-822b-b41c530a29d3.png)

@yehudarav
When I press the pencil it open

**Comment by yehudarav** [comment]
This is the error I get 
![Screenshot from 2021-05-10 13-39-35](https://user-images.githubusercontent.com/50652905/117647116-3dccaf80-b195-11eb-867b-db6021ceda53.png)
