### ISSUE TITLE
Backend - add inheritable attribute to any property to entityType (property of entity)

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#173]
Add a inheritable attribute to any property that allows you determine if its value passes to the the devices it contains. 

If the inheritable value is true, the setting of the  property of the device will pass this value 
to all the devices it contains. 

Remember to set the location for a device that was just added to the group.

**Comment by rivkatzur** [comment]
@yehudarav   
Isn't this field?
![Screenshot from 2021-06-22 09-20-25](https://user-images.githubusercontent.com/6241247/122874103-47703800-d33b-11eb-9a31-28e45d9c0390.png)

**Comment by yehudarav** [comment]
No, the trialfield directory just says if it is possible to change the
field *per trial. * However,
the inheritance copies the values to the object it contains (regardless of
if it is trial-dependent or not).

**Comment by YehuditGrinwald** [comment]
Add prop to  entityTypes property - inheritable (boolean)      
when edit  entityTypes property check inheritable == true -> and then check containsArray and update them.
when push entity to containsArray -> check their parent prop if  inheritable == true -> update the new entity by these prop.

**Comment by YehuditGrinwald** [comment]
מורכובות המשימה מתבטאת בזה שיש צורך להשלים את ההבנה של מבניות הסכמות בדאטהבייס, בניית פונקציות לוגיות - חיפוש הערכים 
 שאותם צריך לעדכן ואת האובייקטים שצריכים להתעדכן בערכים אלה. 
 כל זה תוך שימוש בקוד שכבר כתוב בצורה קצת לא ברורה

**Comment by yehudarav** [comment]
אני מבין. את רוצה שנעשה שיחה כדי להעריך זמן ולראות אולי אפשר לפשט את
הלוגיקה? בנתיים הצטברו לי די הרבה בקשות בשביל השימוש הרגיל

**Comment by YehuditGrinwald** [comment]
@yehudarav 
Is this case correct ?  
entity_00 has child entity_012 and  entity_012 has child entity_456
if we change a prop of entity_012 it will update entity_456 but no longer be same as his parent entity_00

**Comment by yehudarav** [comment]
Yes you are correct

**Comment by YehuditGrinwald** [comment]
@yehudarav Can entity add to another with a different Entity Type?
if yes- should add his inheritable properties although they are not of the same type

**Comment by yehudarav** [comment]
Yes. Entity can add to another entity even if its not his entity type.

In that case the inheritable properties of the father transfer to the son
device.

**Comment by YehuditGrinwald** [comment]
@yehudarav 
אני רואה שבמסך הוספת אנטיטי לטרייל
![image](https://user-images.githubusercontent.com/24703036/128624854-4d541261-f0e5-4d1b-bb88-c6c9bf6f4f29.png)
כרגע מוסיפים את האנטיטי רק עם 
properties 
שהם 
trialField: true
האם זה נכון ?
אם כן -האם הוספת ילד לאבא צריכה להיות עם כל ה
properties 
ללא  תלות ב 
trialField
?

**Comment by YehuditGrinwald** [comment]
@yehudarav 
 if `inheritable` is per trail  the changes will be only on properties with:
    ` inheritable: true trail-set: true`

**Comment by yehudarav** [comment]
לא הבנתי

**Comment by yehudarav** [comment]
ה inheritable רק מציין האם לעדכן את הערך החדש של התכונה לבנים של היישות.

אם התכונה תלויית חזרה (trial) אז הערך החדש יהיה ב trial החדש וב state שלו
(design or deploy).
אם התכונה אינה תלויית חזרה אז היא תשתנה ב properties.

האם זה עוזר?

**Comment by YehuditGrinwald** [comment]
המשפט מעורבב עם אנגלית ולא ברור...

**Comment by YehuditGrinwald** [comment]
@yehudarav כרגע לפי הדיבאג שעשיתי ראיתי שתכונה שהיא לא 
trail-set: true
היא לא בשימוש כשמוסיפים אנטיטי לטרייל. 
לכן גם אם תכונה 
inheritable: true 
לא תעבור לבן

**Comment by YehuditGrinwald** [comment]
so as we talked - inheritable feature is per trial therefor only properties that have:  
` trail-set: true`
 and 
 `inheritable: true`
 will inherit to the child entity.

**Comment by yehudarav** [comment]
Excellent

**Comment by YehuditGrinwald** [comment]
In add entity to trial panel:
 In case user add parent entity and child entity in same session -
the parent doesn't exist in trial yet. so right now user should first add (parent) entity, save and then add child to him.

**Comment by YehuditGrinwald** [comment]
> Yes. Entity can add to another entity even if its not his entity type. In that case the inheritable properties of the father transfer to the son device.
> Yes. Entity can add to another entity even if its not his entity type. In that case the inheritable properties of the father transfer to the son device.

לפי המבנה הנוכחי - לכל entityType יש properties עם מפתחות ייחודיים. לכן כשמוסיפים entity מ type  מסויים ל entity מ type   אחר- אין אפשרות לאחד בין properties ויוצר כפילות.
לדוגמא:
entityType1: locaion key =1
entityType2: locaion key =2
אלה אם כן אני משנה משנים את מבנה המערכת-
יצירת סכמה חדשה של properties ואז כל הוספת property ל entityType יגע מהסכמה הזו.
וכך נוכל להוסיף property מטייפ אחר כי יצביע לאותו מקום
מצורף צילום מסך, אשמח להסביר בשיחה
![Argos_entity child with diff entityType](https://user-images.githubusercontent.com/24703036/128870870-dbc1e696-fe61-49d0-b544-bd6112fa7089.png)

**Comment by YehuditGrinwald** [comment]
דבר נוסף- כרגע כשמוסיפים אנטיטי נפתח הפנל הימני עם כל האנטטיז שעדיין לא משוייכים לטרייל (אנטיטיז שכבר משוייכים לטרייל לא מוצגים.)
מה קורה כשהפנל נפתח כשמוסיפים אנטטי לאנטיטי, איזה אנטיטיז צריכים להיות מוצגים?
אם כל האנטיטיז אז יכול להווצר מצב של הוספת אנטיטי לאבא למרות שעדיין לא משוייך לטרייל.

**Comment by YehuditGrinwald** [comment]
כשמוחקים אנטיטי - יש צורך לבדוק אם יש 
parent entity 
שמצביע עליו ולמחוק גם שם, כדי שלא סתם אבות יצביעו ל
entities 
שלא קיימים

**Comment by YehuditGrinwald** [comment]
> > Yes. Entity can add to another entity even if its not his entity type. In that case the inheritable properties of the father transfer to the son device.
> > Yes. Entity can add to another entity even if its not his entity type. In that case the inheritable properties of the father transfer to the son device.
> 
> ![image](https://user-images.githubusercontent.com/24703036/128871088-eaddb796-48c7-4130-8ea9-4144acc12982.png)
> ![image](https://user-images.githubusercontent.com/24703036/128871373-ff524abc-13b3-4833-b1d2-26449a1f8415.png)
> 
> מצורף צילום מסך, אשמח להסביר בשיחה
> ![Argos_entity child with diff entityType](https://user-images.githubusercontent.com/24703036/128870870-dbc1e696-fe61-49d0-b544-bd6112fa7089.png)

כפי שדיברנו - אנטיטי מטייפ אחר יוריש רק את הלוקיישן

**Comment by YehuditGrinwald** [comment]
when one of `entity trail` updated should update his children

**Comment by yehudarav** [comment]
לא הבנתי. תרצי להתקשר ונדבר?

**Comment by YehuditGrinwald** [comment]
@yehudarav @erasta 
- in  entity type form - new option - Inheritable property. (only when trial-field is true)
- in entities per trial page - add entity to entity - will inherit his property.- (you wont see in UI  yet, will complete by this [task](https://github.com/argosp/trialdash/issues/221 )but  in network you will see new mutation.
@erasta please pull from graph and trialdash - for changes above.

**Comment by yehudarav** [comment]
Excellent.

**Comment by YehuditGrinwald** [comment]
@yehudarav @erasta @shimlinnovate 
new changes deployed: 
In entities per trial page: when update entity property - > if that property was set to Inheritable:true -> it will update his children prop also. 
If his children type of different entityType it will update only location prop (as we talked)
 (done by [this task](https://github.com/argosp/trialdash/issues/221))
@erasta please pull from graph and trialdash - for changes above.
