### ISSUE TITLE
GUI - change devices to entities

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#174]
After the change, a 'device' might be other things (like an asset). 

- Change the 'device' and 'device type' to 'entities' and entities type 
    * We can change only the GUI presentation and not the JSON/backend representation. 
      to save time we will keep it as 'device' and 'device type'. 
- Remove the asset menu. 

**Estimated: 2h**

**Comment by rivkatzur** [comment]
Time: 2h
