### ISSUE TITLE
Setup deployed properties of device (entity)

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#176]
Copy the design properties to the deployed after the user changes the status from deploy to design

**Comment by rivkatzur** [comment]
@yehudarav 
When the user change to deploy and press save it copy the properties to deploy-properties
Do you want to change it?

**Comment by yehudarav** [comment]
I think it was before we talked on the phone, but I will answer.

No, when you change to deploy for the first time, copy it without save
