### ISSUE TITLE
Update the attributes only after save

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#177]
Changing the values of the coordinates through the table does not save into the DB unless 'save' is 
pressed. However,

1. pressing the 'save' takes us out - so its not comfortable. 
2. when we change to the map, it shows the new location, which might confuse the user. 

I suggest that either pressing 'save' keeps us in the same menu or that it is updated automaticaly. 

what do you think?

![Screenshot from 2021-06-08 23-03-07](https://user-images.githubusercontent.com/50652905/121250218-237a1480-c8ae-11eb-8531-6b168d0e6a7e.png)

**Comment by rivkatzur** [comment]
I think that we should have the same behavior in all pages
In all other pages the data is saving only when the user press on 'SAVE'
Just on the map it saving the data automatically
Maybe we can add also here automatically saving but the user has to know about it

**Comment by yehudarav** [comment]
Saving does not work for saving the trials. 
![Screenshot from 2021-07-15 01-34-14](https://user-images.githubusercontent.com/50652905/125701553-9b40ba87-7e4c-4675-b035-48adfcdaac9b.png)
