### ISSUE TITLE
create graphql mutation - add  entity to entity

### ISSUE THREAD

**Issue by YehuditGrinwald** [argosp/trialdash#182]
Mutation will update trial with new entity to parent  entity 
get params: 
`Trial_id`  
`parentEntity_id` - Id of which entity to add 
`newEntity _id`

**Comment by yehudarav** [comment]
Hi, 

So all the setting of entities in other entities is over? Can I start the development of the placement of devices on the 
map with the other software house?

**Comment by YehuditGrinwald** [comment]
לשלוף את הטריל  מה
root


> Hi,
> 
> So all the setting of entities in other entities is over? Can I start the development of the placement of devices on the
> map with the other software house?

Following the task there was a need for a change in the server, need to check that everything is fine after the change and then the code will

**Comment by YehuditGrinwald** [comment]
@yehudarav Sorry, I closed issue by mistake

**Comment by YehuditGrinwald** [comment]
> Hi,
> 
> So all the setting of entities in other entities is over? Can I start the development of the placement of devices on the
> map with the other software house?

I did not feel well the last few days, so I was out of  office. In addition, a horizontal change was required for this task - I started with that. I'll update later

**Comment by YehuditGrinwald** [comment]
@yehudarav @erasta add entity to entity can execute by the new mutation `updateTrialContainsEntities`
