### ISSUE TITLE
Delete entities type does not work 

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#185]
Entities types are not deleted. 

![Screenshot from 2021-07-15 01-35-47](https://user-images.githubusercontent.com/50652905/125701744-9e8ce14c-d1e6-4803-adf9-2b526a1387f1.png)

**Comment by YehuditGrinwald** [comment]
@yehudarav Can not reproduce

**Comment by yehudarav** [comment]
Also true for trial sets
