### ISSUE TITLE
The count of trials is wrong in trial set 

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#186]
The counting of trial is wrong in the trialset 
![Screenshot from 2021-07-15 01-41-20](https://user-images.githubusercontent.com/50652905/125702042-ebb60da9-eb94-4e19-8b5d-183a9ea41d81.png)

**Comment by YehuditGrinwald** [comment]
when upload the code of add entity to parent - check if the bug still exist

**Comment by YehuditGrinwald** [comment]
@yehudarav  fixed. please check

**Comment by YehuditGrinwald** [comment]
> @yehudarav fixed. please check

Can I close ?

**Comment by yehudarav** [comment]
Yes
