### ISSUE TITLE
Dump and load an experiment

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#187]
Add a feature to dump the entire experiment to a JSON file. and the possibility to upload it. 

I think the images should be saved as binary-ascii data in the file. 

If there are problems, lets talk about it.

**Comment by YehuditGrinwald** [comment]
@yehudarav What do you mean 'possibility to upload it.'?  Do you mean to prepare a json file with keys and valus of an experiment  data and I will need to con ert and store in data ?  Export and import data of experiment  ?

**Comment by yehudarav** [comment]
I mean to export and import all the data of the experiment including the
images.

"Do you mean to prepare a json file with keys and valus of an experiment
data and I will need to *con ert* and store in data"

I didn't understand the bold part.

**Comment by HadasS888** [comment]
QA-OK
