### ISSUE TITLE
Adding entities to other doesn't work 

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#194]
Pressing the + sign opens the device list but doesn't adds entities to the list

![Screenshot from 2021-07-21 22-23-59](https://user-images.githubusercontent.com/50652905/126547850-462e41d7-0789-4fe3-90a7-7615a804f06f.png)

**Comment by YehuditGrinwald** [comment]
@yehudarav As I commented [here](https://github.com/argosp/trialdash/issues/172#issuecomment-883999322) I completed the functionality in client and sever except for the design of it meantime- In order for Eran to be able to use that functionality in client map side

**Comment by yehudarav** [comment]
Yes. Thank you everything is ok.
We have some problems on the map component, so eran is fixing it now
