### ISSUE TITLE
Some adjustments to the grid

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#196]
- [x] Is it possible to make sure that at lease one cross is on the (0,0) node
- [ ] Is it possible to add labeling to the grid? (the frequency of them should be determined by the user) 
  Maybe bold lines every ... line grids or something? what do you think?

**Comment by erasta** [comment]
not sure to which grid you refer

**Comment by yehudarav** [comment]
The grid in the device placing component. (the blue one)

**Comment by erasta** [comment]
added lines for zero, bounds and every 5th line
https://github.com/argosp/trialdash/commit/51dc2e3c019cb16621d747ae2b1be43c1fc6b2fc

**Comment by erasta** [comment]
![image](https://user-images.githubusercontent.com/7118772/128377604-bba489db-ae98-4fa1-a1e3-a5a14d716b56.png)
