### ISSUE TITLE
The device Icon. 

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#202]
The icon is the droplet sign which seems as if the location is denoted in by its bottom (the pointed side of the image). 
However, the real location is its center. 

I am not sure about what to do with that, because if we would like to load image that denotes a specific device, it would usually be 
its center. 

Maybe in the future, if we add that feature, the device location icon will also be denoted with a point that identifies the place in it. 
For example if the icon will be an arrow, it will point to the end of the arrow. 

For the meantime, I guess we could correct the current icon such that the tip of the droplet identifies the place.

**Comment by erasta** [comment]
fixed for entity marker only
