### ISSUE TITLE
Removing a group of devices 

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#203]
Can you think of mechanism to remove a group of devices from the map? 

Look at NTA/Release/Test device placement. Switch to Concourse and change it devices to NDIR. 
As you can see there are 30 devices places in that floor. Lets say I want to remove 10 of them. 

You can use the NTA/Release/Test as playing ground.

**Comment by erasta** [comment]
https://user-images.githubusercontent.com/7118772/128330951-01bd5e02-232b-4a17-b1c6-90e9cca66291.mov
