### ISSUE TITLE
Cloning trial keeps previous cloned trial name

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#204]
When cloning a trial, the name of the new trial is similar to the name of the last cloned one. 

Please change to [trial name] clone.

**Comment by YehuditGrinwald** [comment]
@yehudarav  I see it works. maybe it was fixed already?
![image](https://user-images.githubusercontent.com/24703036/133201883-72ad0076-9d75-466c-8989-202099ff371f.png)

**Comment by yehudarav** [comment]
maybe :-). I thought that many of these issues are related.

**Comment by YehuditGrinwald** [comment]
@yehudarav  done. please confirm and close

**Comment by YehuditGrinwald** [comment]
I fixed also click outside of menu will close the menu.
