### ISSUE TITLE
The clone column text in the trial set

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#206]
The clone should be cloned from **[trial name]**/design (or deploy).

**Comment by YehuditGrinwald** [comment]
@yehudarav 
במסך
trialsets
cloneאין עמודה של 
וכן הכפתור
clone 
אין בחירה של 
design\ deploy
לכן לא ברור מה הדרישה של המשימה
![image](https://user-images.githubusercontent.com/24703036/135747677-f3177237-ba80-4b40-902a-42238429ec08.png)

**Comment by YehuditGrinwald** [comment]
Currently we save "cloneFrom":'state' as string.
Restructure in graophql schema is reqired. - change it to object: 
as [ I started to code in issue#206 brunch and](https://github.com/argosp/trialdash/blob/22c59877ff3827b542581bb226f1dfd000184d2d/src/components/TrialContext/Trials/index.jsx#L219) and in [trialgraph](https://github.com/argosp/trialgraph/tree/issue%23206). 
After all, execute MongoDB  query to replace the old string to save as the new obj structure to prevent fail error

**Comment by YehuditGrinwald** [comment]
`cloneFromTrailKey` field was added to `trial`

**Comment by YehuditGrinwald** [comment]
@yehudarav  Done. please confirm and close.
