### ISSUE TITLE
The dialog text when asking user if he wants to leave without changes

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#209]
After the user changes the properties of an entity in a trial and tries to leave a dialog is opened: 
with the text "do you want to leave". Please change to the text "There are unsaved changes. Do you want to leave without saving the changes"? With the default is set on no.

**Comment by YehuditGrinwald** [comment]
@yehudarav  Please attach screenshot.

**Comment by YehuditGrinwald** [comment]
@yehudarav  Do you mean to this page?
![image](https://user-images.githubusercontent.com/24703036/135845031-7d47f734-1049-42d5-9482-979d204bdba0.png)

**Comment by yehudarav** [comment]
Yes

**Comment by YehuditGrinwald** [comment]
@yehudarav Done. Please confirm and close.
