### ISSUE TITLE
Cloning always takes place from one trial.

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#210]
In the NTA experiment, I have tried to clone a release002-004, but it replicated only release001. 

The difference is that in release001, there is a kaijo setting on the main map.

**Comment by YehuditGrinwald** [comment]
@yehudarav Please attach screenshot

**Comment by yehudarav** [comment]
אני אראה אם עדיין יש בעיה אחרי כל התיקונים שלך

**Comment by yehudarav** [comment]
1. Create trial1 and setup few devices on it. 
2. Create trial2 and setup few devices on it 
3. Clone from trial1/design 
4. Now the clonning from trial2/design will take place from trial1 instead of trial2
