### ISSUE TITLE
In the device placement of a trial (the map)

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#211]
On the upper right there is a menu : entities and general. 

Press on general, and then on entities -> The code breaks.

**Comment by YehuditGrinwald** [comment]
@yehudarav @erasta After debugging I see:
The bug happens when map is open - app crashed with error from `LeafletMap`
I  find the error using react-error-boundaries: **Error: Invalid LatLng object: (NaN, NaN)**

**Comment by YehuditGrinwald** [comment]
@erasta  ErrorBoundary code  pushed to `issue#211` branch

**Comment by erasta** [comment]
Crush happened when leaflet map is not shown but was still rendered.
`LeafletMap` is not `TabPanel` aware,  as it is a wrapper for html canvas.
If you rely on `TabPanel` for hiding unfocused components, and somewhere under it there is a `LeafletMap`, use conditional rendering to omit it. Shown on db4f70d lines 528-539.

Personally, i think that the three layers of tabs (trials-entities, general-entities, map-grid) can be reduced to one or two.

**Comment by YehuditGrinwald** [comment]
@yehudarav Please confirm and close
