### ISSUE TITLE
Sorting the devices in the table

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#213]
I think that the easiest way to achieve this is to sort by the order in which the devices were created. 

so we need to add a datetime, when a device was created and sort according to it

**Comment by yehudarav** [comment]
On second thought,now it is sorted (backwards) according to groups that were assigned on the map. 
If we could just sort each group forward, it would be great. 




![Screenshot from 2021-08-04 08-05-13](https://user-images.githubusercontent.com/50652905/128125131-a3477e84-0b5a-4379-9f1f-a247fcace2ce.png)

**Comment by sarareisner** [comment]
@HadasS888  אני צריכה הסבר על זה , אם תוכלי להתקשר אלי אני אשמח 0504170002
