### ISSUE TITLE
Trial table with the trial attributes should be limited in size

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#214]
When there are many attributes, it changes the layout completely
![Screenshot from 2021-08-04 09-07-41](https://user-images.githubusercontent.com/50652905/128130564-2f7d6b57-055c-4b53-8c26-3c3a8a5f4a05.png)

**Comment by yehudarav** [comment]
Maybe just make the icon be in a row?

**Comment by YehuditGrinwald** [comment]
> Maybe just make the icon be in a row?

כן,  הגדרה של האייקונים שתמיד יוצגו בשורה אחת מאוזנת - אומר שכל שאר העמודות יתכווצו ברוחב שלהם

**Comment by YehuditGrinwald** [comment]
@yehudarav באיזה מסכים להגדיר זאת?

**Comment by yehudarav** [comment]
לא בהכרח, אפשר לשים בר גלילה אופקי

**Comment by yehudarav** [comment]
זה רק במסך של ה trials

**Comment by YehuditGrinwald** [comment]
@yehudarav  fixed. please confirm and close
