### ISSUE TITLE
Cloning devices does not work

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#215]
I am trying to clone the devices from release B to release A and it doesn't work (clone in the design stage).

**Comment by YehuditGrinwald** [comment]
@yehudarav Please attach  a screenshot

**Comment by YehuditGrinwald** [comment]
@yehudarav  איפה זה במסכים?

**Comment by yehudarav** [comment]
אני אראה אם יש עדיין בעיה אחרי כל התיקונים שלך

**Comment by HadasS888** [comment]
QA- OK
