### ISSUE TITLE
Cloning devices

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#223]
1. Move the clone devices to the table  screen near the add device (see picture). 
    Remove it from the place that it is now. 

2. Create an option to clone only the devices of the specific type. (where I wrote clone from device) 

![Screenshot from 2021-08-15 18-30-01](https://user-images.githubusercontent.com/50652905/129483835-dfbbd134-1868-41cf-86a0-07b616055725.png)

**Comment by YehuditGrinwald** [comment]
@yehudarav  ברשותך מחלקת את דרישה מספר 2 למשימה חדשה נוספת
#231

**Comment by yehudarav** [comment]
אין בעיה

**Comment by YehuditGrinwald** [comment]
@yehudarav  done. please confirm and close

**Comment by yehudarav** [comment]
ush happened when leaflet map is not shown but was still render
