### ISSUE TITLE
Clone devices from another trialset

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#224]
When cloning devices, allow cloning from another trial-set.  

The mechanism should be similar to what is implemented today, but just with additional level that allows you to choose the 
trial set as well.

**Comment by YehuditGrinwald** [comment]
@yehudarav  please attach UI

**Comment by YehuditGrinwald** [comment]
@yehudarav באיזה מסך זה ? איך יראה העיצוב של הדרישה החדשה?

**Comment by yehudarav** [comment]
במסך ה  clone entity צריך  עוד אפשרוות של בחירת trial-set אחר.

**Comment by HadasS888** [comment]
QA-OK
