### ISSUE TITLE
Create an option to clone only the devices of the specific type.

### ISSUE THREAD

**Issue by YehuditGrinwald** [argosp/trialdash#231]
In trials screen per trial-set
add new option of `Cloning devices `

![image](https://user-images.githubusercontent.com/24703036/133057048-d0dfcb6a-41e7-413d-a7bf-c491fdaf4d0f.png)

**Comment by YehuditGrinwald** [comment]
@yehudarav אנא פרט על המשמעות של הכפתור,
? מה הפעולה בסרבר

**Comment by YehuditGrinwald** [comment]
I already did UI  like this (local):
![image](https://user-images.githubusercontent.com/24703036/133077295-313db6f8-9b41-4bad-9fb7-6c96e622e40d.png)

**Comment by yehudarav** [comment]
Similar to clone entities, but Clones only the devices of that type.

**Comment by YehuditGrinwald** [comment]
@yehudarav I have UI suggestion: 
Instead of more button, we can use the same btn already exist- and add new section in the dialog. as you can see here: 
![image](https://user-images.githubusercontent.com/24703036/133205125-90e9446d-0b6f-4fe1-ac68-655a3c0f63a7.png)

**Comment by YehuditGrinwald** [comment]
@yehudarav נצטרך להחזיר את הכפתור הפנימי של המודל- שאחרי כל הבחירות - לוחצים על כפתור 
submit
ואז עושה  
clone בפועל

**Comment by yehudarav** [comment]
איפה יהיה הכפתור הזה? כחלק מהתפריט של ה clone?

**Comment by YehuditGrinwald** [comment]
@yehudarav 
![image](https://user-images.githubusercontent.com/24703036/133226849-42f3e938-d941-479f-9b98-3ee8ff8b79eb.png)

**Comment by yehudarav** [comment]
מעולה

**Comment by YehuditGrinwald** [comment]
@yehudarav  לתשומת ליבך בדיאלוג של 
clone 
 שנפתח כעת. יש אפשרות לבחור טריל מה שלא ברור- כי אם נמצאים כעת במסך ששייך לטרייל מסוים מה הסיבה לבחירת טרייל
 ?
![image](https://user-images.githubusercontent.com/24703036/133254757-28e4c6ea-f80d-44d6-bca8-0e7b16a63273.png)

**Comment by yehudarav** [comment]
כי רוצים להעתיק את מיקומי המשירים מ trial אחר ל trial שבו את נמצאת עכשיו

**Comment by YehuditGrinwald** [comment]
@yehudarav  Done (see screenshot) please confirm and close.
@erasta I added _Utils_ folder with general functions for reuse (entities manipulation  and more). pull from master in trial-dash to see the changes.

![image](https://user-images.githubusercontent.com/24703036/135490822-ce5ac898-0a5f-403e-9e90-bf7113ba8d5e.png)

**Comment by yehudarav** [comment]
הי, אני לא רואה כפתור להעתיק רק את המכשירים מסוג מסויים

**Comment by YehuditGrinwald** [comment]
@yehudarav כפי שהצעתי, האפשרות לבחור סוג מסויים נמצא בתוך המודל **הקיים** של 
_clone_
ברגע שבוחרים 
`trial`
מוצג האפשרות לבחור
_Select entity type (Optional):_
כפי שאפשר לראות בצילום מסך שצרפתי להערה קודמת

**Comment by yehudarav** [comment]
מצויין, אני אסגור את ה issue
