### ISSUE TITLE
The size of the map grows according with the number of devices

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#241]
הגודל של המפה משתנה לפי מספר המכשירים. 
פעם הייתה גלילה 

![Screenshot from 2021-11-06 09-05-12](https://user-images.githubusercontent.com/50652905/140602525-009bfac5-bb82-4f12-a402-ab76ffcbd5c4.png)

**Comment by sarareisner** [comment]
@yehudarav  do you want the height to be the height of screen or constant height ?
