### ISSUE TITLE
Positions of devices for new trials in the map

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#242]
When creating a new trial, the positions of the devices sometimes depend on the cloning. 

To recreate: 
1. Goto NTA 
2. Goto Trial set New1. 
3. Create a new trial. 
4. Examine the locations of the NDIR devices.

**Comment by yehudarav** [comment]
Correction: 

The devices seem to be set only in the map. (in the example above, you have to go to the concourse map and select the NDIR). 

After refresh, the map shows that NDIR are not set.

**Comment by HadasS888** [comment]
QA- OK
