### ISSUE TITLE
Cloning entities in a trial duplicates them

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#245]
When we clone entities (see figures) and the trial we are cloning from has similar entities to the present trial, the locations should 
be overwritten and not duplicated. 
![duplicates](https://user-images.githubusercontent.com/50652905/153884357-d61e0445-863e-4fd8-91b4-5e7e55fdcca6.png)

![cloneEntities](https://user-images.githubusercontent.com/50652905/153884369-99ae3fcd-ec40-4b37-b619-31eae6aae868.png)

**Comment by sarareisner** [comment]
@yehudarav  I have devices with entity name and name , these devices also can not be duplicated with entity name

**Comment by HadasS888** [comment]
QA- OK
