### ISSUE TITLE
Resolutions conflicts

### ISSUE THREAD

**Issue by oriML** [argosp/trialdash#255]
@HadasS888
There is a difference in the resolution between figma demand to the current project resolution, as you can see here #253 
Figma demand height - 1127px
Current stage height - 637px

It is not clear to me if you want me to fix it and work by Figma demands or stick to the current stage as it is.

If it does relevant to fix it by Figma demands, there is two options I came up with, please refer or offer another solution.

option 1: make components smaller - This can lead to difficulty reading due to low resolution

option 2: expand the height of elements in current stage - This will lead to expanded window view that can make handling harder ( because of scroll between elemetns )

**Comment by HadasS888** [comment]
We had a meeting with the designers. the resolution will change in Figma
