### ISSUE TITLE
add new device(entity)

### ISSUE THREAD

**Issue by oriML** [argosp/trialdash#257]
- [x] dividing the TBP model and GIS model
- [x] visible entity on map button
- [x] styling the map entities
- [x] filter & search logic
- [x] show entity name checkbox
- [x] mark entity/multiple in TBP table
- [x] research of PUT ENTITIES button on SAVE button after DnD
- [x]  add right click on map to open menu for add entity to TBP
- [x] #261
- [x] create add/remove entity (from TBP table on map) popup after right click on entity on map
- [x] #274
- [x] for each selected entity - place it on map by its coordinates
- [x] prev presentation of TBP entities on map
- [x] select map logic

**Comment by orineeman** [comment]
As far as I know, and after checking the app, all this issue's tasks were performed by Ori Levy.
Since it is so, and after checking with Bat Al I close this issue.

**Comment by orineeman** [comment]
As far as I know, and after checking the app, all this issue's tasks were performed by Ori Levy.
Since it is so, and after checking with Bat Al I close this issue.
