### ISSUE TITLE
Assign devices to a trial 

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#26]
Allow the addition of devices to the trial. 
Currently, implement only the table option (the selected option). 

- [ ] List associated. devices
- [ ] Add device

The addition should allow the selection of adding multiple devices at once (consider the very plausible use case of 100 devices) . 

Note that the addition depends on the status of the project that 
can be design or deploy

![Screenshot from 2020-03-22 23-15-58](https://user-images.githubusercontent.com/50652905/77260857-25e55400-6c93-11ea-9c65-f5b50359ba43.png)

**Comment by liorkesos** [comment]
- [ ] List associated. devices
- [. ] Add device

**Comment by rivkatzur** [comment]
https://www.figma.com/proto/geXydxTnUDwpnqmVDhOri3/Argos?scaling=min-zoom&node-id=179%3A321

**Comment by liorkesos** [comment]
it should be based on ...
![image](https://user-images.githubusercontent.com/245027/79744632-5e6a6300-830f-11ea-8a6f-cbc93b131cbf.png)
