### ISSUE TITLE
Position in one shape entities from different types

### ISSUE THREAD

**Issue by oriML** [argosp/trialdash#260]
in the current staged app there is no option to position in one shape entities from different types.
right now as demand we want to enable this option. its involved with the change of logic of existing implementation.
for now the develop continues with the current option. waiting for clarity with this issue.

**Comment by orineeman** [comment]
Currently there is an option to allow different types on the map. But still waiting for the code review, after that we will commit and define bugs to fix

**Comment by orineeman** [comment]
- [ ] fix the function handleMapClick
- [ ] fix the function handlePutEntitiesOnPrev

**Comment by orineeman** [comment]
742e5eb91d669ce8b31856c06bd55cec5965d82f
