### ISSUE TITLE
Deleting an experiment/trial-set/trial/entity does not delete the correct one, but the last one in the list

### ISSUE THREAD

**Issue by HadasS888** [argosp/trialdash#279]
Deleting a trial does not delete the correct trial, but the last trial in the list

**Comment by orineeman** [comment]
Do you mean deletion from the map? At the moment, the behavior of deleting from the map is by right-clicking. to each entity on its own.

**Comment by HadasS888** [comment]
@orineeman Hi, this issue is not related to the map. It's an issue for linnovate. Thanks
