### ISSUE TITLE
Deploy the devices on an image or map

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#28]
The placement of the devices can take place on a map from an openstreetmap (as it is now), 
or on an image that was defined for the experiment. 

The leaflet will get an image name and get from the server the image, origin and scale. 
The image name will be saved to the sever with the location of the device. 

As a first step we concentrate on devices alone.

**Comment by erasta** [comment]
Where are the image details obtained from? through ajax?
Substitute the map with image should be less than a day's work.

**Comment by yehudarav** [comment]
Thats what I had in mind, but we need to clean the details with the other team.
