### ISSUE TITLE
Uploading image map to experiment

### ISSUE THREAD

**Issue by HadasS888** [argosp/trialdash#280]
When uploading image to "Images and locations" in experiment edit - The image proportion change and there is no option to set the correct coordinates of the image map.
** In the old version it used to work fine.

![ExpImange1](https://user-images.githubusercontent.com/65345102/189094666-38b46dd9-7546-46c2-b575-87500b0143b7.png)
![ExpImage2](https://user-images.githubusercontent.com/65345102/189094659-fb74d5e2-fb5f-4e7f-abb9-b57472dabf2c.png)

**Comment by erasta** [comment]
it is possible to change the proportions and coordinates by setting the horizontal and vertical pixel numbers on the left.
but i agree this is not intuitive and comfortable, how do you want it to be?
<img width="700" alt="Screen Shot 2022-11-15 at 8 49 38 AM" src="https://user-images.githubusercontent.com/7118772/201848755-f47b1dfd-025e-4168-883d-e36b31f6b050.png">
<img width="700" alt="Screen Shot 2022-11-15 at 8 49 59 AM" src="https://user-images.githubusercontent.com/7118772/201848873-14bb0abe-dd70-4c92-9063-4b4d95202ad6.png">

**Comment by erasta** [comment]
Done on https://github.com/argosp/trialdash/tree/work-map-standalone-distances
Waiting to be merged when master branch problem is solved.
https://user-images.githubusercontent.com/7118772/205920672-a122041a-ee8e-4f4c-9a44-77b4287e5522.mov

**Comment by erasta** [comment]
Still not merged so lets keep it open

**Comment by erasta** [comment]
done
