### ISSUE TITLE
Tool positining

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#307]
Complete the tool positioning: 

1. hand - place the devices one by one from the to-be-positioned table 
2. point - place the devices in to be positioned at the selected point 
3. arc - place the devices in the to be positioned as an arc 
4. spline -  place the devices in the to be positioned on a spline 
5. line/multiline - places the devices in the to be positioned on a line

See https://www.figma.com/file/geXydxTnUDwpnqmVDhOri3/Argos?node-id=2256%3A38788&t=9frkAj2PapijGfba-0, 
page 'design 2021 for review'.

**Comment by erasta** [comment]
integrate code from here https://github.com/argosp/trialdash/tree/add-new-device-hacked/src/components/EntityPlanner/new/ToBePositionTable/EditTable/ToolsBar

**Comment by erasta** [comment]
<img width="757" alt="Screen Shot 2023-01-24 at 8 13 05 AM" src="https://user-images.githubusercontent.com/7118772/214224016-2af22847-e83a-41ba-9465-5aadfa46b705.png">

**Comment by erasta** [comment]
done
