### ISSUE TITLE
Build is failed

### ISSUE THREAD

**Issue by sarareisner** [argosp/trialdash#312]
@batelkarmi @erasta @yehudarav 
I am trying to build the project but it fails with this error  

Failed to compile.

./src/index.jsx
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at Array.reduceRight (<anonymous>)

I removed everything and run again but same error

**Comment by erasta** [comment]
@sarareisner not sure why it is not building for you.
are cloning argos and its submodules to a new folder and following the instructions on https://github.com/argosp/argos#readme? (did that on my machine a few times without a problem)
if not, can you write the steps you are doing?
if you do, on which step do you get the error above?

**Comment by erasta** [comment]
merged a new version into master, was built ok on CI.
closing this.
