### ISSUE TITLE
Remarks on new placement GUI

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#321]
Hi, 

- [x] 1. The free positioning tool box is opened by default. Could you please remove it? 
- [x] 2. Could you add tooltips on the icons of the tools to describe what they are? 
- [x] 3. How do I select multiple devices in the same area from the map? pressing shift+mouse just 
    focuses me to it. 
- [x] 4. Clicking on the device both adds it to the stack and presents its coordinate. Maybe it would be wiser to 
     add it to the stack after double click? Maybe also add a context menu with add to the stack, edit properties, and other 
     actions? so the user wouldn't have to remember  
- [x] 5. After placement the box of the tool remains visible, can you remove it?

**Comment by erasta** [comment]
done
