### ISSUE TITLE
Mutate device properties on the map

### ISSUE THREAD

**Issue by erasta** [argosp/trialdash#325]
To reproduce: 
1. Right click a device on the map
2. change a property
3. click the green V button to update.

The properties should update correctly, but don't.

call to update the device (which is not working correctly now) is here:
https://github.com/argosp/trialdash/blob/master/src/components/EntityPlanner/EntitiesContext.jsx#L105
![image](https://user-images.githubusercontent.com/7118772/217315866-7a7f0926-d783-4c22-913f-42598b0a442a.png)

**Comment by batelkarmi** [comment]
@shimlinnovate can you help? thanks
