### ISSUE TITLE
Grid is not uniform

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#344]
The grid in unembedded pictures not uniform. Probably it indicates that there is a problem with the distances 
 
![image](https://user-images.githubusercontent.com/50652905/230284269-a004bf66-60e3-4f20-a10f-5ea94167b98a.png)

**Comment by erasta** [comment]
![image](https://github.com/argosp/trialdash/assets/7118772/479309af-5041-4967-bbbd-befa17717c99)
