### ISSUE TITLE
Problem with setting dimensions of embedded image after upload

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#347]
Right after uploading, the image is treated as half its vertical size. 
However, if we save and edit it again, then it works fine. 

![image](https://user-images.githubusercontent.com/50652905/230286154-d7d68da4-edfa-40ea-8fa4-36f54cebc311.png)

**Comment by erasta** [comment]
https://github.com/argosp/trialdash/commit/e97a8360baa9c57ab3fc522339a6a0168ac4fa49
