### ISSUE TITLE
Editing devices on map: Table does not work

### ISSUE THREAD

**Issue by anatkira** [argosp/trialdash#350]
It is not possible to edit the properties of several devices located at the same place. 
Morover, the table that was used to edit the properties of the several devices does not work

**Comment by yehudarav** [comment]
Sometimes this option works. I still havn't figure out when it works and when it doesnt

**Comment by yehudarav** [comment]
Please add a tool that can points without changing the position of the device on the map

**Comment by erasta** [comment]
can you write steps to reproduce? or add image/video? not sure i understand the problem...

**Comment by erasta** [comment]
I think this is fixed.
can you check and if so close? @yehudarav
