### ISSUE TITLE
Editing devices on map: editing location

### ISSUE THREAD

**Issue by anatkira** [argosp/trialdash#351]
It is not possible to edit the location of the devices in the properties. 

The location should be editable (through the table as well).

**Comment by erasta** [comment]
@anatkira @yehudarav what do you mean "through the table as well"? which table?

**Comment by erasta** [comment]
done d02bf1345fdf39486256e413d8824d60f2285bb0

**Comment by erasta** [comment]
done also table f498a13fd7b80dce9eb17e0aeb43724f4954dbb5
