### ISSUE TITLE
Vite server port is hardcoedd

### ISSUE THREAD

**Issue by gadieid** [argosp/trialdash#358]
https://github.com/argosp/trialdash/blob/9107aa448684ca68d2b8a33a4daec1c09c8356f5/vite.config.js#L15

Value shall be taken from .env file in the parent directory (argos) and not hardcoded in file (Or at least docker-compose should be in agreement)

**Comment by erasta** [comment]
@gadieid This should be ok now. 
Note: REACT_APP_PORT on trialdash/.env need to sync with DASHBOARD_PORT on argos/.env

@alex-bondarev-linnovate Thank you! Your comment helped me solve the issue swiftly.
