### ISSUE TITLE
A tool that does not position

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#362]
The current default tool sets the position of the devices in the stack. However, this can lead to unintentional positioning devices that 
were already positioned and were selected just to edit their properties. 

Hence it is necessary to define a an additional tool that would be only a select. This tool will be default. It is also possible to consider 
allowing station by using a right click.

**Comment by erasta** [comment]
done https://github.com/argosp/trialdash/commit/ef793bf40f55410ed8e23633d3cbdfad81b89f13
