### ISSUE TITLE
New toolkit toolbar overlays the devices. 

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#376]
When there are more than 3 devices, the new tool overlaps it. Maybe shit it to the side a bit? 

![Screenshot from 2023-08-22 11-05-06](https://github.com/argosp/trialdash/assets/50652905/e8f37907-c1f8-4288-aa01-39d76d4dcd65)

**Comment by erasta** [comment]
moved to bottom, tell me how it is @yehudarav

**Comment by erasta** [comment]
![image](https://github.com/argosp/trialdash/assets/7118772/5c027545-de30-4c56-8962-7635a533876b)
is this good?
