### ISSUE TITLE
moving bar at the top does not stop

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#377]
Following the deletion of multiple devices, there is a green moving status bar at the top of the screen. 

However, it does not stop moving after the deletion is complete. This confuses the users to think that the
deletion is still in progress. 

![Screenshot from 2023-08-22 11-39-33](https://github.com/argosp/trialdash/assets/50652905/16ebf3dc-9980-4f3f-9ab4-104e3e3bb796)

**Comment by erasta** [comment]
fixed e97acee4b3e3226c8ac8b58760bd8f5db004f4f2
