### ISSUE TITLE
Bad CSV format

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#379]
The downloaded file does not split the location into values. 
That is, 

name,entitiesTypeName,Location,Height
"Gilat","Sonic","{'name':'OSMMap','coordinates':[32.10002639514208,34.86030578613282]}",
"Ramat Hovav","Sonic","{'name':'OSMMap','coordinates':[32.0528987905317,34.86030578613282]}",

Where it should be 
name,entitiesTypeName,MapName,Longitude,Latitude,Height
Gilat,Sonic,OSMMap,32.10002639514208,34.86030578613282,
Ramat Hovav,Sonic,OSMMap,32.0528987905317,34.86030578613282,

**Comment by erasta** [comment]
fixed https://github.com/argosp/trialdash/commit/2c8eb60e164578a28e9560f7709a88528692b8a1
