### ISSUE TITLE
Telling the user to Refresh manually after upload

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#382]
Since refresh is needed (and we won't fix it now), just write after the upload -> please refresh manually somewhere that 
is very visible.

**Comment by yehudarav** [comment]
Also after cloning devices.

**Comment by erasta** [comment]
![image](https://github.com/argosp/trialdash/assets/7118772/df4e8c1a-0806-4fd0-9450-604825ca4969)
message with refresh button
