### ISSUE TITLE
Loading CSV does not work

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#389]
The loading of the CSV fails to place the devices if they are not already placed on the map.

**Comment by yehudarav** [comment]
Still doesnt work. 
Try the file in TEST1_PETRI/my trial set/a trial. 

[test1.csv](https://github.com/argosp/trialdash/files/12587267/test1.csv)

**Comment by yehudarav** [comment]
When loading this file: 
[test1.csv](https://github.com/argosp/trialdash/files/12591159/test1.csv)
in this trial
https://argos.new-aks-stage.linnovate.net/experiments/64f49209d65c947e9c864c95/trial-sets/7f822d58-7301-45d7-8782-d3c5bda246dd/trials

We can see the counter just skips several devices in the beginning from 3 to 13.

**Comment by erasta** [comment]
that specific trial was corrupted, other places are fixed.
added error messages if that happens again
![image](https://github.com/argosp/trialdash/assets/7118772/a742fe31-843a-4715-8897-7df31f7a707e)
