### ISSUE TITLE
Copying entity locations to a trial 

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#55]
Allow copying the entities from a different trial. 

When copying the user should choose whether he copies from 
from the other trial design or deploy.

**Comment by shimlinnovate** [comment]
Waiting for design from Edan @yehudarav @edenden1 @rivkatzur

**Comment by YehuditGrinwald** [comment]
@yehudarav Need more info

**Comment by YehuditGrinwald** [comment]
@yehudarav  when copy from deploy:  should copy as is  or copy  the changes entities as if they were the originals?
when copy from design: should copy only only the design source entities?
In all case the copy items will be with status "design"?
