### ISSUE TITLE
GraphQL update entity. 

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#56]
Build a graphQL query that updates a single field in an entity, experiment, a trial or a trial set.

**Comment by rivkatzur** [comment]
Add `action: "update"` to the mutation
and it will update only the data you send
and not delete data that doesn't send
**note: you must send key**

for example if you send this it will update the name and not delete other data(description, maps...): 
mutation {
  addUpdateExperiment(
    **action: "update"**
    uid: "75694ae0-95eb-11eb-a7e7-03735ce719f8"
    **key**: "fdbc3b25-1de3-4dc2-9654-8648929cac19"
    name: "change only name"
  ) {
    name
    description
    key
    state
    status
    maps {
      imageUrl
      imageName
      lower
      right
      upper
      left
      embedded
    }
  }
}
