### ISSUE TITLE
Update device location through leaflet

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#64]
Allow the leaflet component update  the location after they are placed. 

The leaflet will list either 
1. devices that were already assigned to the trial. 
2.  All devices (according to type). 

Option 2 is what implemented today. 

**Case 1. - show only assigned devices** 
The leaflet will have a switch (true/false) that will change the list only to devices that 
were already assigned to the trial. 
Changing location will save the new location in the db. 

Steps required: 
1. Rivka - please publish below the graphql query to list only the devices that were assigned 
                to the trial. 
2. Rivka - please publish the graphql needed to update the location of the device. 
3. Eran  - please implement the necessary changes to the leaflet. 

Note that the structure of the location record is given in issue #49

**Case 2. - show all assigned devices** 
Deploying a device in this state will update its location and 
assign it to the trial. 
This is relevant both in design and deploy modes of the trial. 

1. Rivka - please make sure that assigning location to devices that are not assigned 
                to the trial will assign them.

**Comment by kaplanlior** [comment]
@rivkatzur, please assign to @erasta after providing the info @yehudarav asked for.

**Comment by rivkatzur** [comment]
**Update the location of the device**
**And assigned device to trial if not assigned**

trialdash/src/components/TrialContext/TrialForm/utils/trialMutationUpdate.js


```
mutation {
  addUpdateTrial(
    action: "update"
    uid: "uid"
    key: "trial key"
    experimentId: "experiment Id"
    trialSetKey: "trial set key"
    entities / deployEntities: [
      {
        key: "device key"
        type: "device / asset"
        typeKey: "deviceType key"
        properties: [
          {
            key: "device property key"
            val: "{\"name\":\"OSMMap\",\"coordinates\":[\"x\",\"y\"]}"
          }
        ]
      }
    ]
  ) {
    key
    created
    status
    id
    name
    trialSetKey
    numberOfDevices
    state
    properties {
      key
      val
    }
    entities {
      key
      typeKey
      type
      properties {
        key
        val
      }
    }
    deployedEntities {
      key
      typeKey
      type
      properties {
        key
        val
      }
    }
  }
}

```

**Comment by shimlinnovate** [comment]
Hi you can check the first part as described in the previous comment @kaplanlior @erasta

**Comment by rivkatzur** [comment]
**Graphql query to list only the devices that were assigned to the trial**

In the devicesQuery you can set the trialKey,
and then you will receive only devices that  assigned to the trial.

```
{  
  devices(  
    experimentId: "5eb2628382bcc90925285661"  
    deviceTypeKey: "f2794d32-610a-4a4b-a0d7-93ca25abce7c"
    trialKey: "f937d4f1-df15-4d3d-bd00-b372d1bb8104"
  ) {
    key
    id
    name
    deviceTypeKey
    properties {
      key
      val
    }
  }
}
```

In this case you will receive only devices that assigned to the trial **and the assigning saved in db**
if we want to show the devices before saved the assigning in db, We need to send them from our component.

**Comment by erasta** [comment]
Is it possible to wrap the relevant queries/mutations with JS functions?
Would greatly improve readability and increase decoupling.

**Comment by rivkatzur** [comment]
@erasta 

The DevicePlanner Component has a props called updateLocation.
This function add the entity to the trial and set the location.
Example of using:


 ```
this.props.updateLocation({
      key: "47125d77-afaa-4b4d-8a06-3c9b5c2dd45a",
      type: "device",
      typeKey: "f2794d32-610a-4a4b-a0d7-93ca25abce7c",
      properties: [
             {
                     key: "201cf175-b326-4785-b812-7ddc853f33f6",
                     val: JSON.stringify({name:"OSMMap",coordinates:[789,147]})
              }
       ]
})
```

**Comment by rivkatzur** [comment]
@erasta   

What do you need in the query function?
All devices?
Or only the assigned devices?
Also the deviceTypes?
I need more info for this.

**Comment by erasta** [comment]
> @erasta
> 
> What do you need in the query function?

@rivkatzur 

Thank you.
I'll compose a short list of queries/mutations that the map interface needs.
I believe that having such interfaces will aid us in identifying problems, as the params will be defined, in contrary to the map component building the graphql strings.

**Comment by erasta** [comment]
> The DevicePlanner Component has a props called updateLocation.
> This function add the entity to the trial and set the location.
> Example of using:
> 
> ```
> this.props.updateLocation({
>      key: "47125d77-afaa-4b4d-8a06-3c9b5c2dd45a",
>      type: "device",
>      typeKey: "f2794d32-610a-4a4b-a0d7-93ca25abce7c",
>      properties: [
>             {
>                     key: "201cf175-b326-4785-b812-7ddc853f33f6",
>                     val: JSON.stringify({name:"OSMMap",coordinates:[789,147]})
>              }
>       ]
> })
> ```

@rivkatzur Few clarifications about the params:
- `type: "device"` is this a constant or the name of the device?
- All device come initially with a single property that has a value of null, is this the position? should i assign it the position once it is placed?  
if not, then is there a way to generate more keys inherited in the system?
- Are you using the position anywhere else in the system and it has to have a specific format, or can i use my own stringifying methods there?
```
>      properties: [
>             {
>                     key: "201cf175-b326-4785-b812-7ddc853f33f6",
>                     val: JSON.stringify({name:"OSMMap",coordinates:[789,147]})
>              }
>       ]
```

**Comment by erasta** [comment]
Could you please take a look at my use of updateLocation on https://github.com/argosp/trialdash/blob/bc0908f45cb1f9e2b6744c9f6ce7a836caaa45be/src/components/DevicePlanner/index.jsx#L68
and tell me why do you think i get this error from `QueryManager.mutate`
```
Uncaught (in promise) Error: GraphQL error: Cannot read property 'data' of undefined
    at new t (bundle.esm.js:73)
    at e.<anonymous> (bundle.esm.js:1248)
    at tslib.es6.js:208
    at Object.next (tslib.es6.js:138)
    at tslib.es6.js:111
    at new Promise (<anonymous>)
    at s (tslib.es6.js:88)
.
.
.
```

**Comment by shimlinnovate** [comment]
@erasta Hi Eran, can you write the list, please?

**Comment by rivkatzur** [comment]
@erasta 
-  **`type: "device"` is this a constant**
-  The position key is taken from the deviceType properties,
   There is a property that his type is `location` and you have to use the key of this property.
-  The position format was defined by Yehuda.

- I fixed the `updateLocation`, (There was some code not on master).

**Comment by erasta** [comment]
@rivkatzur 

> * The position key is taken from the deviceType properties,
>   There is a property that his type is `location` and you have to use the key of this property.

Not all device types have that property and it changes between device types.  
Is that intentional?  
Device with type that doesn't have a location can't be placed on the map? Shouldn't even be on the list on the panel?  

> * The position format was defined by Yehuda.

Can you state that format?  
is it `JSON.stringify({name:"OSMMap",coordinates:[789,147]})`?  
should it be passed to updateLocation as a string that is later `JSON.parse` or would we have a double stringification there?  

> * I fixed the `updateLocation`, (There was some code not on master).

Even after the fix, it doesn't work. But maybe that's because of the wrong uuid.

**Comment by erasta** [comment]
Update:

When calling `updateLocation` with `JSON.stringify({name:"OSMMap",coordinates:[789,147]})` graphql fails with `Uncaught (in promise) Error: GraphQL error: getaddrinfo ENOTFOUND`

When calling `updateLocation` with `JSON.stringify([789,147])` the location property is updated to `null` or doesn't get updated at all.

@rivkatzur can you check please?

**Comment by YehuditGrinwald** [comment]
@erasta @yehudarav  Is it work?

**Comment by erasta** [comment]
> @erasta @yehudarav Is it work?

If you mean "does the leaflet updates the location of the devices", yes it does.
On "old" trials/trialsets there is a problem. I suggest deleting them to reduce confusion.

Also, this issue as @yehudarav created it seems to contain other changes needed.
Maybe create other issues for those?

**Comment by YehuditGrinwald** [comment]
@erasta yes, other changes in new issues will be better.

**Comment by erasta** [comment]
Done (both changes)
