### ISSUE TITLE
Slow map rendering

### ISSUE THREAD

**Issue by erasta** [argosp/trialdash#75]

**Comment by shimlinnovate** [comment]
@erasta  from the WhatsApp yesterday I understand its a task we should check, please confirm

**Comment by shimlinnovate** [comment]
כול להיות שיש במערכת משהו שנקרא subscriptions (כנראה subscriptions-transport-ws) שמשתלט על רוב קריאות ה http/s? כנראה בגלל זה או משהו דומה המפה נטענת ממש לאט. תודה
![WhatsApp Image 2020-06-21 at 18 32 38](https://user-images.githubusercontent.com/63184626/85287416-e3533380-b49c-11ea-9f8e-6d9fcc53f891.jpeg)

**Comment by erasta** [comment]
yes that is correct @shimlinnovate

**Comment by shimlinnovate** [comment]
@LevLevenberg please help @YehuditGrinwald with this issue

**Comment by YehuditGrinwald** [comment]
@shimlinnovate @yehudarav fixed, please check

**Comment by erasta** [comment]
still looks stuck. 
the error on the side is: `WebSocket connection to 'wss://argos.new-aks-stage.linnovate.net/subscriptions' failed: Error during WebSocket handshake: Unexpected response code: 200`
![image](https://user-images.githubusercontent.com/7118772/85998570-a5618c80-ba13-11ea-9a72-30e8a0127bd2.png)

**Comment by erasta** [comment]
I would check if invalidate on the leaflet could fix that problem

**Comment by YehuditGrinwald** [comment]
@yehudarav @shimlinnovate @adishua @erasta  After a deep exploration of the map library in an attempt to resolve
There are two issues:

- Map gets stuck - sometimes happens. after screen resizing it is fine.

- Slow map (I couldn't recover - I tried on office wifi and phone hotspot.)

After conversation with @erasta he said that he will try to fix it and do not interfere with the map code and all things related to it from the DevicePlanner folder and down.

I opened new issue - #83 - about subscription error that describe below.

**Comment by yehudarav** [comment]
The map component does not load at all.... 
I tried hard refresh (and I get the same result from different computers). 

![Screenshot from 2020-07-07 14-28-29](https://user-images.githubusercontent.com/50652905/86774062-db7bbd80-c05e-11ea-934b-6c619265b272.png)

**Comment by erasta** [comment]
Fixed this bug, @yehudarav please check.
