### ISSUE TITLE
Configure tile server url for the leaflet component

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#76]
It is necessary to configure the tile server url for the leaflet configuration. 

The configuration should be set before loading (a configuration file) of the system, 
it will not change during the operation. 

The leaflet can have several sources, so we need a place in the configuration file 
to define the list of urls and an graphQL query that will return the list of url's.

**Comment by YehuditGrinwald** [comment]
Instead basemaps url in TileLayer- add an option to get map from server. (for work without network )

**Comment by erasta** [comment]
@YehuditGrinwald would add a UI for the combo box of the tileserver on the trial.
The selection would include the tileserver (`openstreetmap`/`cartojs`/etc) or an image.
In case of an image, bounds should also be given (lower-right and top-left corners, as 4 numbers)
The `DevicePlanner` component would accept a property in the form of a struct
`TileLayer={{url, attribution, bounds}}`

**Comment by YehuditGrinwald** [comment]
>would add a UI for the combo box of the tileserver on the trial.

@yehudarav  should be on trial editor?

**Comment by YehuditGrinwald** [comment]
@erasta  Please send me screenshot of new UI that you described appear ,where it should be locate ?

**Comment by erasta** [comment]
@YehuditGrinwald This is the current UI which is hard coded.
@yehudarav wants it to be on the trial or trialset level, not the map level. That means, outside of this page.
Or did i not understand your question?
![image](https://user-images.githubusercontent.com/7118772/87293602-3a33b200-c50b-11ea-8de4-8bea09913fa4.png)

**Comment by yehudarav** [comment]
Itnshould be a configurstion at the server level. The user doesnt need
access to it.

**Comment by erasta** [comment]
> Itnshould be a configurstion at the server level. The user doesnt need access to it.
@yehudarav now it is hardcoded on the react code at the server.
if that is not sufficient, where do you want it to be changeable?

**Comment by YehuditGrinwald** [comment]
> > Itnshould be a configurstion at the server level. The user doesnt need access to it.
> 
> @yehudarav now it is hardcoded on the react code at the server.
> if that is not sufficient, **where** do you want it to be changeable? 

@yehudarav where do you want it to be changeable? 
and who will have access to change these trial map settings?
To completely understand the requirement please add more  info as a screen ui,  user behavior  and the desired result you expect to get.

**Comment by yehudarav** [comment]
Hi, it should be in a configuration file at the service level. I don't think we need UI for this. (except for documentation). 
that is, it cannot be changed after the service is up.

**Comment by YehuditGrinwald** [comment]
@yehudarav  what the configuration file contains? list of urls? 
can I have example ? 
I need it for the behavior of the  leaflet component.

**Comment by YehuditGrinwald** [comment]
After discussion with @yehudarav and @erasta 
The requirement is to make map config file (json/ yml) and allows to edit it before server upload.
The file content (urls and other param) will be forward to the leaflet component.
@erasta please describe here what variable you expect to receive in leaflet  component. string of url or more?

**Comment by YehuditGrinwald** [comment]
@yehudarav 
please provide the changes you want in _edit experiment_  form
![image](https://user-images.githubusercontent.com/24703036/89727233-4e47d200-da2b-11ea-8045-31fcaf97a23d.png)

**Comment by YehuditGrinwald** [comment]
UI inputs, displays  as table:
1. image url as string
2. bounds of 4 numeric inputs as an array.
3.  attribution as string 
4. image nickname as string

**Comment by YehuditGrinwald** [comment]
created [new task](https://github.com/argosp/trialdash/issues/88) related to edit experiment.

**Comment by YehuditGrinwald** [comment]
@erasta @yehudarav I added new file named `.env` , `.env.production` (exist already).
 `.env` - for developers
`.env.production`- for production 
these will render when server start. files contain variables, each variable has key and value.
When you would like to edit the file and add new variables (to set map IP etc ..) it should be in that syntax:
uppercase, start with `REACT_APP` and continue  with `_` between each word.
for example:
`REACT_APP_MAP_ATTRIBUTION= https://carto.com`
@erasta in react side you can access the variables that way: `process.env.REACT_APP_MAP_URL
` in your component. for example:
replace[ this line](https://github.com/argosp/trialdash/blob/36096e9d3e87a120af17ad357b19f99e7580ce80/src/components/DevicePlanner/DeviceEditor/DeviceMap.jsx#L28) with:
 attribution={`&copy; <a href="${process.env.REACT_APP_MAP_ATTRIBUTION}">Carto</a> contributors`}

**Comment by erasta** [comment]
Integrated into map https://github.com/argosp/trialdash/commit/c3e246cdb666989e0f74885f84389f8d46abf4e4
Bug can be closed if ok.

**Comment by erasta** [comment]
switching the conversation here:

> @YehuditGrinwald As you see on your example, that would contain the name of the of the tile provider hardcoded. In the case where we switch to another provider that would also change.
Since this rarely change, please leave it containing html, as our users are accustomed to a little html.
In the case where you definitely don't html there, i'll organize a table inside the DeviceMap
