### ISSUE TITLE
Subscription error in devtools network

### ISSUE THREAD

**Issue by YehuditGrinwald** [argosp/trialdash#83]
Issue was started describe by @erasta  in #75 
open devtools ->console->sometimes got on error: `WebSocket connection to 'wss://argos.new-aks-stage.linnovate.net/subscriptions' failed: Error during WebSocket handshake: Unexpected response code: 200`
![subError](https://user-images.githubusercontent.com/24703036/86094389-1dce5900-bab9-11ea-9f85-8b11eb84edf3.png)

devtools-> network-> there are multiple of subscription requests calls in some of them with `wait `status.
Need To check the `subscriptions-transport-ws` [library](https://www.npmjs.com/package/subscriptions-transport-ws) (insert to code by @vladislav-vasilyev )

**Comment by erasta** [comment]
this is still happening, and now its slows my network heavily
![image](https://user-images.githubusercontent.com/7118772/128317913-791bf93e-2557-4e21-9e80-56712cf748b1.png)

**Comment by YehuditGrinwald** [comment]
@erasta 
It fixed on this [brunch](https://github.com/argosp/argos/tree/ssl) by @kirillfomichev 
that brunch did not merge to master because it was not checked yet

**Comment by kirillfomichev** [comment]
@erasta try https://github.com/argosp/argos/tree/ssl  

need add argos.new-aks-stage.linnovate.net to /etc/hosts

127.0.0.1 argos.new-aks-stage.linnovate.net

web ports ssl:
https://argos.new-aks-stage.linnovate.net:4433

**Comment by YehuditGrinwald** [comment]
@erasta what's the status of this issue? did you check the @kirillfomichev 's brunch ?
